// Generated by jextract

package ls.pc.host.boundary;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AbiRange {
 *     uint32_t start_line;
 *     uint32_t start_character;
 *     uint32_t end_line;
 *     uint32_t end_character;
 * }
 * }
 */
public class AbiRange {

    AbiRange() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        boundary_h.C_INT.withName("start_line"),
        boundary_h.C_INT.withName("start_character"),
        boundary_h.C_INT.withName("end_line"),
        boundary_h.C_INT.withName("end_character")
    ).withName("AbiRange");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt start_line$LAYOUT = (OfInt)$LAYOUT.select(groupElement("start_line"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t start_line
     * }
     */
    public static final OfInt start_line$layout() {
        return start_line$LAYOUT;
    }

    private static final long start_line$OFFSET = $LAYOUT.byteOffset(groupElement("start_line"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t start_line
     * }
     */
    public static final long start_line$offset() {
        return start_line$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t start_line
     * }
     */
    public static int start_line(MemorySegment struct) {
        return struct.get(start_line$LAYOUT, start_line$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t start_line
     * }
     */
    public static void start_line(MemorySegment struct, int fieldValue) {
        struct.set(start_line$LAYOUT, start_line$OFFSET, fieldValue);
    }

    private static final OfInt start_character$LAYOUT = (OfInt)$LAYOUT.select(groupElement("start_character"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t start_character
     * }
     */
    public static final OfInt start_character$layout() {
        return start_character$LAYOUT;
    }

    private static final long start_character$OFFSET = $LAYOUT.byteOffset(groupElement("start_character"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t start_character
     * }
     */
    public static final long start_character$offset() {
        return start_character$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t start_character
     * }
     */
    public static int start_character(MemorySegment struct) {
        return struct.get(start_character$LAYOUT, start_character$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t start_character
     * }
     */
    public static void start_character(MemorySegment struct, int fieldValue) {
        struct.set(start_character$LAYOUT, start_character$OFFSET, fieldValue);
    }

    private static final OfInt end_line$LAYOUT = (OfInt)$LAYOUT.select(groupElement("end_line"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t end_line
     * }
     */
    public static final OfInt end_line$layout() {
        return end_line$LAYOUT;
    }

    private static final long end_line$OFFSET = $LAYOUT.byteOffset(groupElement("end_line"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t end_line
     * }
     */
    public static final long end_line$offset() {
        return end_line$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t end_line
     * }
     */
    public static int end_line(MemorySegment struct) {
        return struct.get(end_line$LAYOUT, end_line$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t end_line
     * }
     */
    public static void end_line(MemorySegment struct, int fieldValue) {
        struct.set(end_line$LAYOUT, end_line$OFFSET, fieldValue);
    }

    private static final OfInt end_character$LAYOUT = (OfInt)$LAYOUT.select(groupElement("end_character"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t end_character
     * }
     */
    public static final OfInt end_character$layout() {
        return end_character$LAYOUT;
    }

    private static final long end_character$OFFSET = $LAYOUT.byteOffset(groupElement("end_character"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t end_character
     * }
     */
    public static final long end_character$offset() {
        return end_character$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t end_character
     * }
     */
    public static int end_character(MemorySegment struct) {
        return struct.get(end_character$LAYOUT, end_character$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t end_character
     * }
     */
    public static void end_character(MemorySegment struct, int fieldValue) {
        struct.set(end_character$LAYOUT, end_character$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

