// Generated by jextract

package ls.pc.host.boundary;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class boundary_h extends boundary_h$shared {

    boundary_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int ABI_VERSION = (int)2L;
    /**
     * {@snippet lang=c :
     * #define ABI_VERSION 2
     * }
     */
    public static int ABI_VERSION() {
        return ABI_VERSION;
    }
    private static final int STATUS_OK = (int)0L;
    /**
     * {@snippet lang=c :
     * #define STATUS_OK 0
     * }
     */
    public static int STATUS_OK() {
        return STATUS_OK;
    }
    private static final int MAGIC = (int)1111576652L;
    /**
     * {@snippet lang=c :
     * #define MAGIC 1111576652
     * }
     */
    public static int MAGIC() {
        return MAGIC;
    }
    private static final int STATUS_PANIC = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define STATUS_PANIC -1
     * }
     */
    public static int STATUS_PANIC() {
        return STATUS_PANIC;
    }
    private static final int STATUS_BAD_ARG = (int)-2L;
    /**
     * {@snippet lang=c :
     * #define STATUS_BAD_ARG -2
     * }
     */
    public static int STATUS_BAD_ARG() {
        return STATUS_BAD_ARG;
    }
    private static final int STATUS_ABI_MISMATCH = (int)-3L;
    /**
     * {@snippet lang=c :
     * #define STATUS_ABI_MISMATCH -3
     * }
     */
    public static int STATUS_ABI_MISMATCH() {
        return STATUS_ABI_MISMATCH;
    }
    private static final int STATUS_DECODE = (int)-4L;
    /**
     * {@snippet lang=c :
     * #define STATUS_DECODE -4
     * }
     */
    public static int STATUS_DECODE() {
        return STATUS_DECODE;
    }
    private static final int STATUS_ALLOC = (int)-5L;
    /**
     * {@snippet lang=c :
     * #define STATUS_ALLOC -5
     * }
     */
    public static int STATUS_ALLOC() {
        return STATUS_ALLOC;
    }
    private static final int STATUS_INTERNAL = (int)-6L;
    /**
     * {@snippet lang=c :
     * #define STATUS_INTERNAL -6
     * }
     */
    public static int STATUS_INTERNAL() {
        return STATUS_INTERNAL;
    }
    private static final int STATUS_NOT_YET = (int)-7L;
    /**
     * {@snippet lang=c :
     * #define STATUS_NOT_YET -7
     * }
     */
    public static int STATUS_NOT_YET() {
        return STATUS_NOT_YET;
    }
}

