// Generated by jextract

package ls.pc.host.boundary;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct LocationRecord {
 *     struct BlobStr uri;
 *     struct AbiRange range;
 *     uint32_t origin;
 * }
 * }
 */
public class LocationRecord {

    LocationRecord() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        BlobStr.layout().withName("uri"),
        AbiRange.layout().withName("range"),
        boundary_h.C_INT.withName("origin")
    ).withName("LocationRecord");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout uri$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("uri"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct BlobStr uri
     * }
     */
    public static final GroupLayout uri$layout() {
        return uri$LAYOUT;
    }

    private static final long uri$OFFSET = $LAYOUT.byteOffset(groupElement("uri"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct BlobStr uri
     * }
     */
    public static final long uri$offset() {
        return uri$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct BlobStr uri
     * }
     */
    public static MemorySegment uri(MemorySegment struct) {
        return struct.asSlice(uri$OFFSET, uri$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct BlobStr uri
     * }
     */
    public static void uri(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, uri$OFFSET, uri$LAYOUT.byteSize());
    }

    private static final GroupLayout range$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("range"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct AbiRange range
     * }
     */
    public static final GroupLayout range$layout() {
        return range$LAYOUT;
    }

    private static final long range$OFFSET = $LAYOUT.byteOffset(groupElement("range"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct AbiRange range
     * }
     */
    public static final long range$offset() {
        return range$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct AbiRange range
     * }
     */
    public static MemorySegment range(MemorySegment struct) {
        return struct.asSlice(range$OFFSET, range$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct AbiRange range
     * }
     */
    public static void range(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, range$OFFSET, range$LAYOUT.byteSize());
    }

    private static final OfInt origin$LAYOUT = (OfInt)$LAYOUT.select(groupElement("origin"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t origin
     * }
     */
    public static final OfInt origin$layout() {
        return origin$LAYOUT;
    }

    private static final long origin$OFFSET = $LAYOUT.byteOffset(groupElement("origin"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t origin
     * }
     */
    public static final long origin$offset() {
        return origin$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t origin
     * }
     */
    public static int origin(MemorySegment struct) {
        return struct.get(origin$LAYOUT, origin$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t origin
     * }
     */
    public static void origin(MemorySegment struct, int fieldValue) {
        struct.set(origin$LAYOUT, origin$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

