// Generated by jextract

package ls.pc.host.boundary;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef int32_t (*PcResolveFn)(struct LsStr {
 *     const uint8_t *ptr;
 *     uint32_t len;
 * }, struct LsStr {
 *     const uint8_t *ptr;
 *     uint32_t len;
 * }, const uint8_t *, uint32_t, struct LsBuf {
 *     uint8_t *ptr;
 *     uint32_t len;
 * } *)
 * }
 */
public final class PcResolveFn {

    private PcResolveFn() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment target_id, MemorySegment symbol, MemorySegment item_ptr, int item_len, MemorySegment out);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        boundary_h.C_INT,
        LsStr.layout(),
        LsStr.layout(),
        boundary_h.C_POINTER,
        boundary_h.C_INT,
        boundary_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = boundary_h.upcallHandle(PcResolveFn.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(PcResolveFn.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr, MemorySegment target_id, MemorySegment symbol, MemorySegment item_ptr, int item_len, MemorySegment out) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, target_id, symbol, item_ptr, item_len, out);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

