// Generated by jextract

package ls.pc.host.boundary;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct PcVtable {
 *     uint64_t abi_version;
 *     PcRequestFn register_target;
 *     PcRequestFn did_open;
 *     PcRequestFn did_change;
 *     PcUriFn did_close;
 *     PcQueryFn completion;
 *     PcResolveFn completion_resolve;
 *     PcQueryFn hover;
 *     PcQueryFn signature_help;
 *     PcQueryFn definition;
 *     PcQueryFn type_definition;
 *     PcQueryFn prepare_rename;
 *     PcStatusOutFn plugin_status;
 *     PcVoidFn restart_instances;
 *     PcVoidFn shutdown;
 *     PcSpawnDispatchFn spawn_dispatch;
 * }
 * }
 */
public class PcVtable {

    PcVtable() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        boundary_h.C_LONG.withName("abi_version"),
        boundary_h.C_POINTER.withName("register_target"),
        boundary_h.C_POINTER.withName("did_open"),
        boundary_h.C_POINTER.withName("did_change"),
        boundary_h.C_POINTER.withName("did_close"),
        boundary_h.C_POINTER.withName("completion"),
        boundary_h.C_POINTER.withName("completion_resolve"),
        boundary_h.C_POINTER.withName("hover"),
        boundary_h.C_POINTER.withName("signature_help"),
        boundary_h.C_POINTER.withName("definition"),
        boundary_h.C_POINTER.withName("type_definition"),
        boundary_h.C_POINTER.withName("prepare_rename"),
        boundary_h.C_POINTER.withName("plugin_status"),
        boundary_h.C_POINTER.withName("restart_instances"),
        boundary_h.C_POINTER.withName("shutdown"),
        boundary_h.C_POINTER.withName("spawn_dispatch")
    ).withName("PcVtable");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong abi_version$LAYOUT = (OfLong)$LAYOUT.select(groupElement("abi_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t abi_version
     * }
     */
    public static final OfLong abi_version$layout() {
        return abi_version$LAYOUT;
    }

    private static final long abi_version$OFFSET = $LAYOUT.byteOffset(groupElement("abi_version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t abi_version
     * }
     */
    public static final long abi_version$offset() {
        return abi_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t abi_version
     * }
     */
    public static long abi_version(MemorySegment struct) {
        return struct.get(abi_version$LAYOUT, abi_version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t abi_version
     * }
     */
    public static void abi_version(MemorySegment struct, long fieldValue) {
        struct.set(abi_version$LAYOUT, abi_version$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcRequestFn register_target
     * }
     */
    public final static class register_target {

        private register_target() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            boundary_h.C_POINTER,
            boundary_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(register_target.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(register_target.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout register_target$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("register_target"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcRequestFn register_target
     * }
     */
    public static final AddressLayout register_target$layout() {
        return register_target$LAYOUT;
    }

    private static final long register_target$OFFSET = $LAYOUT.byteOffset(groupElement("register_target"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcRequestFn register_target
     * }
     */
    public static final long register_target$offset() {
        return register_target$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcRequestFn register_target
     * }
     */
    public static MemorySegment register_target(MemorySegment struct) {
        return struct.get(register_target$LAYOUT, register_target$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcRequestFn register_target
     * }
     */
    public static void register_target(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(register_target$LAYOUT, register_target$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcRequestFn did_open
     * }
     */
    public final static class did_open {

        private did_open() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            boundary_h.C_POINTER,
            boundary_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(did_open.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(did_open.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout did_open$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("did_open"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcRequestFn did_open
     * }
     */
    public static final AddressLayout did_open$layout() {
        return did_open$LAYOUT;
    }

    private static final long did_open$OFFSET = $LAYOUT.byteOffset(groupElement("did_open"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcRequestFn did_open
     * }
     */
    public static final long did_open$offset() {
        return did_open$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcRequestFn did_open
     * }
     */
    public static MemorySegment did_open(MemorySegment struct) {
        return struct.get(did_open$LAYOUT, did_open$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcRequestFn did_open
     * }
     */
    public static void did_open(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(did_open$LAYOUT, did_open$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcRequestFn did_change
     * }
     */
    public final static class did_change {

        private did_change() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            boundary_h.C_POINTER,
            boundary_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(did_change.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(did_change.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout did_change$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("did_change"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcRequestFn did_change
     * }
     */
    public static final AddressLayout did_change$layout() {
        return did_change$LAYOUT;
    }

    private static final long did_change$OFFSET = $LAYOUT.byteOffset(groupElement("did_change"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcRequestFn did_change
     * }
     */
    public static final long did_change$offset() {
        return did_change$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcRequestFn did_change
     * }
     */
    public static MemorySegment did_change(MemorySegment struct) {
        return struct.get(did_change$LAYOUT, did_change$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcRequestFn did_change
     * }
     */
    public static void did_change(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(did_change$LAYOUT, did_change$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcUriFn did_close
     * }
     */
    public final static class did_close {

        private did_close() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            LsStr.layout()
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(did_close.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(did_close.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout did_close$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("did_close"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcUriFn did_close
     * }
     */
    public static final AddressLayout did_close$layout() {
        return did_close$LAYOUT;
    }

    private static final long did_close$OFFSET = $LAYOUT.byteOffset(groupElement("did_close"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcUriFn did_close
     * }
     */
    public static final long did_close$offset() {
        return did_close$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcUriFn did_close
     * }
     */
    public static MemorySegment did_close(MemorySegment struct) {
        return struct.get(did_close$LAYOUT, did_close$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcUriFn did_close
     * }
     */
    public static void did_close(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(did_close$LAYOUT, did_close$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcQueryFn completion
     * }
     */
    public final static class completion {

        private completion() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            LsStr.layout(),
            boundary_h.C_INT,
            boundary_h.C_INT,
            boundary_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(completion.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(completion.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, int _x2, MemorySegment _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout completion$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("completion"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcQueryFn completion
     * }
     */
    public static final AddressLayout completion$layout() {
        return completion$LAYOUT;
    }

    private static final long completion$OFFSET = $LAYOUT.byteOffset(groupElement("completion"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcQueryFn completion
     * }
     */
    public static final long completion$offset() {
        return completion$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcQueryFn completion
     * }
     */
    public static MemorySegment completion(MemorySegment struct) {
        return struct.get(completion$LAYOUT, completion$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcQueryFn completion
     * }
     */
    public static void completion(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(completion$LAYOUT, completion$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcResolveFn completion_resolve
     * }
     */
    public final static class completion_resolve {

        private completion_resolve() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, int _x3, MemorySegment _x4);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            LsStr.layout(),
            LsStr.layout(),
            boundary_h.C_POINTER,
            boundary_h.C_INT,
            boundary_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(completion_resolve.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(completion_resolve.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, int _x3, MemorySegment _x4) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout completion_resolve$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("completion_resolve"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcResolveFn completion_resolve
     * }
     */
    public static final AddressLayout completion_resolve$layout() {
        return completion_resolve$LAYOUT;
    }

    private static final long completion_resolve$OFFSET = $LAYOUT.byteOffset(groupElement("completion_resolve"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcResolveFn completion_resolve
     * }
     */
    public static final long completion_resolve$offset() {
        return completion_resolve$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcResolveFn completion_resolve
     * }
     */
    public static MemorySegment completion_resolve(MemorySegment struct) {
        return struct.get(completion_resolve$LAYOUT, completion_resolve$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcResolveFn completion_resolve
     * }
     */
    public static void completion_resolve(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(completion_resolve$LAYOUT, completion_resolve$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcQueryFn hover
     * }
     */
    public final static class hover {

        private hover() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            LsStr.layout(),
            boundary_h.C_INT,
            boundary_h.C_INT,
            boundary_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(hover.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(hover.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, int _x2, MemorySegment _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout hover$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hover"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcQueryFn hover
     * }
     */
    public static final AddressLayout hover$layout() {
        return hover$LAYOUT;
    }

    private static final long hover$OFFSET = $LAYOUT.byteOffset(groupElement("hover"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcQueryFn hover
     * }
     */
    public static final long hover$offset() {
        return hover$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcQueryFn hover
     * }
     */
    public static MemorySegment hover(MemorySegment struct) {
        return struct.get(hover$LAYOUT, hover$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcQueryFn hover
     * }
     */
    public static void hover(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hover$LAYOUT, hover$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcQueryFn signature_help
     * }
     */
    public final static class signature_help {

        private signature_help() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            LsStr.layout(),
            boundary_h.C_INT,
            boundary_h.C_INT,
            boundary_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(signature_help.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(signature_help.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, int _x2, MemorySegment _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout signature_help$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("signature_help"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcQueryFn signature_help
     * }
     */
    public static final AddressLayout signature_help$layout() {
        return signature_help$LAYOUT;
    }

    private static final long signature_help$OFFSET = $LAYOUT.byteOffset(groupElement("signature_help"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcQueryFn signature_help
     * }
     */
    public static final long signature_help$offset() {
        return signature_help$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcQueryFn signature_help
     * }
     */
    public static MemorySegment signature_help(MemorySegment struct) {
        return struct.get(signature_help$LAYOUT, signature_help$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcQueryFn signature_help
     * }
     */
    public static void signature_help(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(signature_help$LAYOUT, signature_help$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcQueryFn definition
     * }
     */
    public final static class definition {

        private definition() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            LsStr.layout(),
            boundary_h.C_INT,
            boundary_h.C_INT,
            boundary_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(definition.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(definition.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, int _x2, MemorySegment _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout definition$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("definition"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcQueryFn definition
     * }
     */
    public static final AddressLayout definition$layout() {
        return definition$LAYOUT;
    }

    private static final long definition$OFFSET = $LAYOUT.byteOffset(groupElement("definition"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcQueryFn definition
     * }
     */
    public static final long definition$offset() {
        return definition$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcQueryFn definition
     * }
     */
    public static MemorySegment definition(MemorySegment struct) {
        return struct.get(definition$LAYOUT, definition$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcQueryFn definition
     * }
     */
    public static void definition(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(definition$LAYOUT, definition$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcQueryFn type_definition
     * }
     */
    public final static class type_definition {

        private type_definition() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            LsStr.layout(),
            boundary_h.C_INT,
            boundary_h.C_INT,
            boundary_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(type_definition.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(type_definition.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, int _x2, MemorySegment _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout type_definition$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("type_definition"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcQueryFn type_definition
     * }
     */
    public static final AddressLayout type_definition$layout() {
        return type_definition$LAYOUT;
    }

    private static final long type_definition$OFFSET = $LAYOUT.byteOffset(groupElement("type_definition"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcQueryFn type_definition
     * }
     */
    public static final long type_definition$offset() {
        return type_definition$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcQueryFn type_definition
     * }
     */
    public static MemorySegment type_definition(MemorySegment struct) {
        return struct.get(type_definition$LAYOUT, type_definition$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcQueryFn type_definition
     * }
     */
    public static void type_definition(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(type_definition$LAYOUT, type_definition$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcQueryFn prepare_rename
     * }
     */
    public final static class prepare_rename {

        private prepare_rename() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            LsStr.layout(),
            boundary_h.C_INT,
            boundary_h.C_INT,
            boundary_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(prepare_rename.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(prepare_rename.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, int _x2, MemorySegment _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout prepare_rename$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("prepare_rename"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcQueryFn prepare_rename
     * }
     */
    public static final AddressLayout prepare_rename$layout() {
        return prepare_rename$LAYOUT;
    }

    private static final long prepare_rename$OFFSET = $LAYOUT.byteOffset(groupElement("prepare_rename"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcQueryFn prepare_rename
     * }
     */
    public static final long prepare_rename$offset() {
        return prepare_rename$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcQueryFn prepare_rename
     * }
     */
    public static MemorySegment prepare_rename(MemorySegment struct) {
        return struct.get(prepare_rename$LAYOUT, prepare_rename$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcQueryFn prepare_rename
     * }
     */
    public static void prepare_rename(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(prepare_rename$LAYOUT, prepare_rename$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcStatusOutFn plugin_status
     * }
     */
    public final static class plugin_status {

        private plugin_status() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            boundary_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(plugin_status.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(plugin_status.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout plugin_status$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("plugin_status"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcStatusOutFn plugin_status
     * }
     */
    public static final AddressLayout plugin_status$layout() {
        return plugin_status$LAYOUT;
    }

    private static final long plugin_status$OFFSET = $LAYOUT.byteOffset(groupElement("plugin_status"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcStatusOutFn plugin_status
     * }
     */
    public static final long plugin_status$offset() {
        return plugin_status$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcStatusOutFn plugin_status
     * }
     */
    public static MemorySegment plugin_status(MemorySegment struct) {
        return struct.get(plugin_status$LAYOUT, plugin_status$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcStatusOutFn plugin_status
     * }
     */
    public static void plugin_status(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(plugin_status$LAYOUT, plugin_status$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcVoidFn restart_instances
     * }
     */
    public final static class restart_instances {

        private restart_instances() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply();
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT);

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(restart_instances.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(restart_instances.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout restart_instances$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("restart_instances"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcVoidFn restart_instances
     * }
     */
    public static final AddressLayout restart_instances$layout() {
        return restart_instances$LAYOUT;
    }

    private static final long restart_instances$OFFSET = $LAYOUT.byteOffset(groupElement("restart_instances"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcVoidFn restart_instances
     * }
     */
    public static final long restart_instances$offset() {
        return restart_instances$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcVoidFn restart_instances
     * }
     */
    public static MemorySegment restart_instances(MemorySegment struct) {
        return struct.get(restart_instances$LAYOUT, restart_instances$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcVoidFn restart_instances
     * }
     */
    public static void restart_instances(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(restart_instances$LAYOUT, restart_instances$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcVoidFn shutdown
     * }
     */
    public final static class shutdown {

        private shutdown() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply();
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT);

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(shutdown.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(shutdown.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout shutdown$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("shutdown"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcVoidFn shutdown
     * }
     */
    public static final AddressLayout shutdown$layout() {
        return shutdown$LAYOUT;
    }

    private static final long shutdown$OFFSET = $LAYOUT.byteOffset(groupElement("shutdown"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcVoidFn shutdown
     * }
     */
    public static final long shutdown$offset() {
        return shutdown$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcVoidFn shutdown
     * }
     */
    public static MemorySegment shutdown(MemorySegment struct) {
        return struct.get(shutdown$LAYOUT, shutdown$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcVoidFn shutdown
     * }
     */
    public static void shutdown(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(shutdown$LAYOUT, shutdown$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcSpawnDispatchFn spawn_dispatch
     * }
     */
    public final static class spawn_dispatch {

        private spawn_dispatch() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(int _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            boundary_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(spawn_dispatch.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(spawn_dispatch.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, int _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout spawn_dispatch$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("spawn_dispatch"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcSpawnDispatchFn spawn_dispatch
     * }
     */
    public static final AddressLayout spawn_dispatch$layout() {
        return spawn_dispatch$LAYOUT;
    }

    private static final long spawn_dispatch$OFFSET = $LAYOUT.byteOffset(groupElement("spawn_dispatch"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcSpawnDispatchFn spawn_dispatch
     * }
     */
    public static final long spawn_dispatch$offset() {
        return spawn_dispatch$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcSpawnDispatchFn spawn_dispatch
     * }
     */
    public static MemorySegment spawn_dispatch(MemorySegment struct) {
        return struct.get(spawn_dispatch$LAYOUT, spawn_dispatch$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcSpawnDispatchFn spawn_dispatch
     * }
     */
    public static void spawn_dispatch(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(spawn_dispatch$LAYOUT, spawn_dispatch$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

