// Generated by jextract

package ls.pc.host.boundary;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct Position {
 *     uint32_t line;
 *     uint32_t character;
 * }
 * }
 */
public class Position {

    Position() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        boundary_h.C_INT.withName("line"),
        boundary_h.C_INT.withName("character")
    ).withName("Position");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt line$LAYOUT = (OfInt)$LAYOUT.select(groupElement("line"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t line
     * }
     */
    public static final OfInt line$layout() {
        return line$LAYOUT;
    }

    private static final long line$OFFSET = $LAYOUT.byteOffset(groupElement("line"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t line
     * }
     */
    public static final long line$offset() {
        return line$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t line
     * }
     */
    public static int line(MemorySegment struct) {
        return struct.get(line$LAYOUT, line$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t line
     * }
     */
    public static void line(MemorySegment struct, int fieldValue) {
        struct.set(line$LAYOUT, line$OFFSET, fieldValue);
    }

    private static final OfInt character$LAYOUT = (OfInt)$LAYOUT.select(groupElement("character"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t character
     * }
     */
    public static final OfInt character$layout() {
        return character$LAYOUT;
    }

    private static final long character$OFFSET = $LAYOUT.byteOffset(groupElement("character"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t character
     * }
     */
    public static final long character$offset() {
        return character$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t character
     * }
     */
    public static int character(MemorySegment struct) {
        return struct.get(character$LAYOUT, character$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t character
     * }
     */
    public static void character(MemorySegment struct, int fieldValue) {
        struct.set(character$LAYOUT, character$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

