// Generated by jextract

package ls.pc.host.boundary;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct RustVtable {
 *     uint64_t abi_version;
 *     uint64_t layout_canary;
 *     AllocFn alloc;
 *     FreeFn free;
 *     LogFn log;
 *     RegisterPcVtableFn register_pc_vtable;
 *     PcDispatchLoopFn pc_dispatch_loop;
 *     SymbolDefinitionFn symbol_definition;
 * }
 * }
 */
public class RustVtable {

    RustVtable() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        boundary_h.C_LONG.withName("abi_version"),
        boundary_h.C_LONG.withName("layout_canary"),
        boundary_h.C_POINTER.withName("alloc"),
        boundary_h.C_POINTER.withName("free"),
        boundary_h.C_POINTER.withName("log"),
        boundary_h.C_POINTER.withName("register_pc_vtable"),
        boundary_h.C_POINTER.withName("pc_dispatch_loop"),
        boundary_h.C_POINTER.withName("symbol_definition")
    ).withName("RustVtable");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong abi_version$LAYOUT = (OfLong)$LAYOUT.select(groupElement("abi_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t abi_version
     * }
     */
    public static final OfLong abi_version$layout() {
        return abi_version$LAYOUT;
    }

    private static final long abi_version$OFFSET = $LAYOUT.byteOffset(groupElement("abi_version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t abi_version
     * }
     */
    public static final long abi_version$offset() {
        return abi_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t abi_version
     * }
     */
    public static long abi_version(MemorySegment struct) {
        return struct.get(abi_version$LAYOUT, abi_version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t abi_version
     * }
     */
    public static void abi_version(MemorySegment struct, long fieldValue) {
        struct.set(abi_version$LAYOUT, abi_version$OFFSET, fieldValue);
    }

    private static final OfLong layout_canary$LAYOUT = (OfLong)$LAYOUT.select(groupElement("layout_canary"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t layout_canary
     * }
     */
    public static final OfLong layout_canary$layout() {
        return layout_canary$LAYOUT;
    }

    private static final long layout_canary$OFFSET = $LAYOUT.byteOffset(groupElement("layout_canary"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t layout_canary
     * }
     */
    public static final long layout_canary$offset() {
        return layout_canary$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t layout_canary
     * }
     */
    public static long layout_canary(MemorySegment struct) {
        return struct.get(layout_canary$LAYOUT, layout_canary$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t layout_canary
     * }
     */
    public static void layout_canary(MemorySegment struct, long fieldValue) {
        struct.set(layout_canary$LAYOUT, layout_canary$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * AllocFn alloc
     * }
     */
    public final static class alloc {

        private alloc() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(int _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_POINTER,
            boundary_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(alloc.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(alloc.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, int _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout alloc$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("alloc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AllocFn alloc
     * }
     */
    public static final AddressLayout alloc$layout() {
        return alloc$LAYOUT;
    }

    private static final long alloc$OFFSET = $LAYOUT.byteOffset(groupElement("alloc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AllocFn alloc
     * }
     */
    public static final long alloc$offset() {
        return alloc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AllocFn alloc
     * }
     */
    public static MemorySegment alloc(MemorySegment struct) {
        return struct.get(alloc$LAYOUT, alloc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AllocFn alloc
     * }
     */
    public static void alloc(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(alloc$LAYOUT, alloc$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * FreeFn free
     * }
     */
    public final static class free {

        private free() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            boundary_h.C_POINTER,
            boundary_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(free.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(free.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout free$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("free"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * FreeFn free
     * }
     */
    public static final AddressLayout free$layout() {
        return free$LAYOUT;
    }

    private static final long free$OFFSET = $LAYOUT.byteOffset(groupElement("free"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * FreeFn free
     * }
     */
    public static final long free$offset() {
        return free$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * FreeFn free
     * }
     */
    public static MemorySegment free(MemorySegment struct) {
        return struct.get(free$LAYOUT, free$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * FreeFn free
     * }
     */
    public static void free(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(free$LAYOUT, free$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * LogFn log
     * }
     */
    public final static class log {

        private log() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(int _x0, MemorySegment _x1, int _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            boundary_h.C_INT,
            boundary_h.C_POINTER,
            boundary_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(log.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(log.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, int _x0, MemorySegment _x1, int _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout log$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("log"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * LogFn log
     * }
     */
    public static final AddressLayout log$layout() {
        return log$LAYOUT;
    }

    private static final long log$OFFSET = $LAYOUT.byteOffset(groupElement("log"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * LogFn log
     * }
     */
    public static final long log$offset() {
        return log$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * LogFn log
     * }
     */
    public static MemorySegment log(MemorySegment struct) {
        return struct.get(log$LAYOUT, log$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * LogFn log
     * }
     */
    public static void log(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(log$LAYOUT, log$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * RegisterPcVtableFn register_pc_vtable
     * }
     */
    public final static class register_pc_vtable {

        private register_pc_vtable() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            boundary_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(register_pc_vtable.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(register_pc_vtable.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout register_pc_vtable$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("register_pc_vtable"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RegisterPcVtableFn register_pc_vtable
     * }
     */
    public static final AddressLayout register_pc_vtable$layout() {
        return register_pc_vtable$LAYOUT;
    }

    private static final long register_pc_vtable$OFFSET = $LAYOUT.byteOffset(groupElement("register_pc_vtable"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RegisterPcVtableFn register_pc_vtable
     * }
     */
    public static final long register_pc_vtable$offset() {
        return register_pc_vtable$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RegisterPcVtableFn register_pc_vtable
     * }
     */
    public static MemorySegment register_pc_vtable(MemorySegment struct) {
        return struct.get(register_pc_vtable$LAYOUT, register_pc_vtable$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RegisterPcVtableFn register_pc_vtable
     * }
     */
    public static void register_pc_vtable(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(register_pc_vtable$LAYOUT, register_pc_vtable$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * PcDispatchLoopFn pc_dispatch_loop
     * }
     */
    public final static class pc_dispatch_loop {

        private pc_dispatch_loop() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(int _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            boundary_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(pc_dispatch_loop.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(pc_dispatch_loop.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, int _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout pc_dispatch_loop$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pc_dispatch_loop"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PcDispatchLoopFn pc_dispatch_loop
     * }
     */
    public static final AddressLayout pc_dispatch_loop$layout() {
        return pc_dispatch_loop$LAYOUT;
    }

    private static final long pc_dispatch_loop$OFFSET = $LAYOUT.byteOffset(groupElement("pc_dispatch_loop"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PcDispatchLoopFn pc_dispatch_loop
     * }
     */
    public static final long pc_dispatch_loop$offset() {
        return pc_dispatch_loop$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PcDispatchLoopFn pc_dispatch_loop
     * }
     */
    public static MemorySegment pc_dispatch_loop(MemorySegment struct) {
        return struct.get(pc_dispatch_loop$LAYOUT, pc_dispatch_loop$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PcDispatchLoopFn pc_dispatch_loop
     * }
     */
    public static void pc_dispatch_loop(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pc_dispatch_loop$LAYOUT, pc_dispatch_loop$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * SymbolDefinitionFn symbol_definition
     * }
     */
    public final static class symbol_definition {

        private symbol_definition() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            LsStr.layout(),
            LsStr.layout(),
            boundary_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(symbol_definition.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(symbol_definition.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout symbol_definition$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("symbol_definition"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SymbolDefinitionFn symbol_definition
     * }
     */
    public static final AddressLayout symbol_definition$layout() {
        return symbol_definition$LAYOUT;
    }

    private static final long symbol_definition$OFFSET = $LAYOUT.byteOffset(groupElement("symbol_definition"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SymbolDefinitionFn symbol_definition
     * }
     */
    public static final long symbol_definition$offset() {
        return symbol_definition$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SymbolDefinitionFn symbol_definition
     * }
     */
    public static MemorySegment symbol_definition(MemorySegment struct) {
        return struct.get(symbol_definition$LAYOUT, symbol_definition$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SymbolDefinitionFn symbol_definition
     * }
     */
    public static void symbol_definition(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(symbol_definition$LAYOUT, symbol_definition$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

