#pragma once

/* Generated by cbindgen from the ls-pc-abi Rust ABI. Do not edit by hand; run scripts/regen-pc-abi-bindings.sh. */

#include <stdint.h>

// Boundary contract version, checked at registration.
#define ABI_VERSION 1

// Shared status codes returned by every boundary function (`0` = ok).
#define STATUS_OK 0

// A Rust panic (or Java `Throwable`) was caught at the boundary.
#define STATUS_PANIC -1

// A required argument was null or otherwise invalid.
#define STATUS_BAD_ARG -2

// `abi_version` / layout canary disagreement at registration.
#define STATUS_ABI_MISMATCH -3

// A response/request payload failed to decode.
#define STATUS_DECODE -4

// A response allocation failed.
#define STATUS_ALLOC -5

// An unexpected internal error.
#define STATUS_INTERNAL -6

// The envelope magic (`"LPAB"` little-endian).
#define MAGIC 1111576652

#define WORKSPACE 0

#define SYNTHETIC 1

#define PLUGIN 2

// A borrowed UTF-8 string argument (no NUL), valid only for the call.
typedef struct LsStr {
    const uint8_t *ptr;
    uint32_t len;
} LsStr;

// A borrowed opaque byte buffer argument (an encoded payload), valid only for
// the call.
typedef struct LsBytes {
    const uint8_t *ptr;
    uint32_t len;
} LsBytes;

// A Rust-owned response buffer returned to the caller through an out-param.
// The caller frees it with the Rust vtable `free`.
typedef struct LsBuf {
    uint8_t *ptr;
    uint32_t len;
} LsBuf;

// A string inside a response buffer's trailing blob: `offset` is relative to
// the blob start, `len` is the byte length.
typedef struct BlobStr {
    uint32_t offset;
    uint32_t len;
} BlobStr;

// A zero-based `line`/`character` position (UTF-16 code units, as LSP).
typedef struct Position {
    uint32_t line;
    uint32_t character;
} Position;

// A flattened `[start, end)` range (avoids a nested struct in records).
typedef struct AbiRange {
    uint32_t start_line;
    uint32_t start_character;
    uint32_t end_line;
    uint32_t end_character;
} AbiRange;

// A definition/reference location record: a blob-referenced uri, a range, and
// a `DefinitionOrigin` ordinal (`0` when the op carries no origin).
typedef struct LocationRecord {
    struct BlobStr uri;
    struct AbiRange range;
    uint32_t origin;
} LocationRecord;

// Response-buffer allocation: Rust owns all cross-boundary memory. `alloc`
// returns a buffer of `size` bytes (or null); the consumer later `free`s it.
typedef uint8_t *(*AllocFn)(uint32_t size);

// Frees an `alloc`-obtained buffer of the given size.
typedef void (*FreeFn)(uint8_t *ptr, uint32_t size);

// Island → Rust structured logging.
typedef void (*LogFn)(int32_t level, const uint8_t *ptr, uint32_t len);

// A request carrying an encoded payload buffer (register_target/did_open/
// did_change). Returns a status code.
typedef int32_t (*PcRequestFn)(const uint8_t *params_ptr, uint32_t params_len);

// A request carrying a single uri (did_close).
typedef int32_t (*PcUriFn)(struct LsStr uri);

// A position query (completion/hover/signature_help/definition/
// type_definition/prepare_rename): writes its response payload to `out`.
typedef int32_t (*PcQueryFn)(struct LsStr uri, uint32_t line, uint32_t character, struct LsBuf *out);

// Completion-item resolve: the owning target, the item's symbol, and the
// encoded item; writes the enriched item to `out`.
typedef int32_t (*PcResolveFn)(struct LsStr target_id,
                               struct LsStr symbol,
                               const uint8_t *item_ptr,
                               uint32_t item_len,
                               struct LsBuf *out);

// A no-argument query that writes a response payload to `out` (plugin_status).
typedef int32_t (*PcStatusOutFn)(struct LsBuf *out);

// A no-argument lifecycle op (restart_instances/shutdown).
typedef int32_t (*PcVoidFn)(void);

// Spawns a fresh loaned dispatch thread for the given generation.
typedef int32_t (*PcSpawnDispatchFn)(uint32_t generation);

// The 15-op PC vtable. Slot order is the cross-language contract.
typedef struct PcVtable {
    uint64_t abi_version;
    PcRequestFn register_target;
    PcRequestFn did_open;
    PcRequestFn did_change;
    PcUriFn did_close;
    PcQueryFn completion;
    PcResolveFn completion_resolve;
    PcQueryFn hover;
    PcQueryFn signature_help;
    PcQueryFn definition;
    PcQueryFn type_definition;
    PcQueryFn prepare_rename;
    PcStatusOutFn plugin_status;
    PcVoidFn restart_instances;
    PcVoidFn shutdown;
    PcSpawnDispatchFn spawn_dispatch;
} PcVtable;

// Island → Rust registration of the PC vtable; returns a status code.
typedef int32_t (*RegisterPcVtableFn)(const struct PcVtable *pc);

// Entry point a Java-loaned thread enters and never returns from.
typedef void (*PcDispatchLoopFn)(int32_t worker_index);

// Index-backed cross-file go-to-definition callback: resolves `symbol` (with
// the requesting buffer `from_uri`) into a locations response written to `out`.
typedef int32_t (*SymbolDefinitionFn)(struct LsStr symbol, struct LsStr from_uri, struct LsBuf *out);

// Index-backed workspace method search callback (the PC `SymbolSearch.
// searchMethods` seam): resolves `query` (with the requesting build target
// `bsp_target_id`) into a method-hits response written to `out`.
typedef int32_t (*SearchMethodsFn)(struct LsStr query, struct LsStr bsp_target_id, struct LsBuf *out);

// The Rust vtable handed to the premain. The island mirrors this layout
// through jextract-generated FFM bindings; `layout_canary` is recomputed
// independently and a mismatch refuses registration.
typedef struct RustVtable {
    uint64_t abi_version;
    uint64_t layout_canary;
    AllocFn alloc;
    FreeFn free;
    LogFn log;
    RegisterPcVtableFn register_pc_vtable;
    PcDispatchLoopFn pc_dispatch_loop;
    SymbolDefinitionFn symbol_definition;
    SearchMethodsFn search_methods;
} RustVtable;


