// Generated by jextract

package spike.boundary;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class boundary_h extends boundary_h$shared {

    boundary_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int ABI_VERSION = (int)1L;
    /**
     * {@snippet lang=c :
     * #define ABI_VERSION 1
     * }
     */
    public static int ABI_VERSION() {
        return ABI_VERSION;
    }
}

