// Generated by jextract

package spike.boundary;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct PcVtable {
 *     uint64_t abi_version;
 *     EchoFn echo;
 * }
 * }
 */
public class PcVtable {

    PcVtable() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        boundary_h.C_LONG.withName("abi_version"),
        boundary_h.C_POINTER.withName("echo")
    ).withName("PcVtable");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong abi_version$LAYOUT = (OfLong)$LAYOUT.select(groupElement("abi_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t abi_version
     * }
     */
    public static final OfLong abi_version$layout() {
        return abi_version$LAYOUT;
    }

    private static final long abi_version$OFFSET = $LAYOUT.byteOffset(groupElement("abi_version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t abi_version
     * }
     */
    public static final long abi_version$offset() {
        return abi_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t abi_version
     * }
     */
    public static long abi_version(MemorySegment struct) {
        return struct.get(abi_version$LAYOUT, abi_version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t abi_version
     * }
     */
    public static void abi_version(MemorySegment struct, long fieldValue) {
        struct.set(abi_version$LAYOUT, abi_version$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * EchoFn echo
     * }
     */
    public final static class echo {

        private echo() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2, int _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            boundary_h.C_INT,
            boundary_h.C_POINTER,
            boundary_h.C_INT,
            boundary_h.C_POINTER,
            boundary_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = boundary_h.upcallHandle(echo.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(echo.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2, int _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout echo$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("echo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * EchoFn echo
     * }
     */
    public static final AddressLayout echo$layout() {
        return echo$LAYOUT;
    }

    private static final long echo$OFFSET = $LAYOUT.byteOffset(groupElement("echo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * EchoFn echo
     * }
     */
    public static final long echo$offset() {
        return echo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * EchoFn echo
     * }
     */
    public static MemorySegment echo(MemorySegment struct) {
        return struct.get(echo$LAYOUT, echo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * EchoFn echo
     * }
     */
    public static void echo(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(echo$LAYOUT, echo$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

