#pragma once

/* Generated by cbindgen from the ls-jvm-spike Rust ABI. Do not edit by hand; run scripts/regen-spike-bindings.sh. */

#include <stdint.h>

// Boundary contract version, checked at registration.
#define ABI_VERSION 1

// Island → Rust structured logging.
typedef void (*LogFn)(int32_t level, const uint8_t *ptr, int32_t len);

// The PC-side echo op, exposed by the island as an FFM upcall stub:
// `echo(in_ptr, in_len, out_ptr, out_cap) -> written_len | negative status`.
typedef int32_t (*EchoFn)(const uint8_t *in_ptr, int32_t in_len, uint8_t *out_ptr, int32_t out_cap);

// The PC vtable the island registers, built as FFM upcall stubs.
typedef struct PcVtable {
    uint64_t abi_version;
    EchoFn echo;
} PcVtable;

// Island → Rust registration of the PC vtable; returns a status code.
typedef int32_t (*RegisterPcVtableFn)(const struct PcVtable *pc);

// Entry point a Java-loaned thread enters and never returns from.
typedef void (*PcDispatchLoopFn)(int32_t worker_index);

// The Rust vtable handed to the premain (its address is the agent argument).
// The island mirrors this layout through jextract-generated FFM bindings.
//
// `layout_canary` is a deterministic hash the island independently recomputes
// from the ABI struct sizes/offsets at bootstrap; a mismatch means the two
// sides disagree on the binary layout, and the island refuses to register (so
// boot is refused).
typedef struct RustVtable {
    uint64_t abi_version;
    uint64_t layout_canary;
    LogFn log;
    RegisterPcVtableFn register_pc_vtable;
    PcDispatchLoopFn pc_dispatch_loop;
} RustVtable;
